// Code generated by protoc-gen-go.
// source: anauth/cl/clpb/cl.proto
// DO NOT EDIT!

/*
Package clpb is a generated protocol buffer package.

It is generated from these files:
	anauth/cl/clpb/cl.proto

It has these top-level messages:
	Request
	Response
	Empty
	SchnorrGroup
	PedersenParams
	PubKey
	Params
	PublicParams
	CredIssueRequest
	Cred
	IssuedCred
	CredUpdateRequest
	CredProof
	FiatShamir
	FiatShamirAlsoNeg
*/
package clpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	// Types that are valid to be assigned to Type:
	//	*Request_Empty
	//	*Request_RegKey
	//	*Request_CredIssue
	//	*Request_CredProve
	Type isRequest_Type `protobuf_oneof:"type"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isRequest_Type interface {
	isRequest_Type()
}

type Request_Empty struct {
	Empty *Empty `protobuf:"bytes,1,opt,name=empty,oneof"`
}
type Request_RegKey struct {
	RegKey string `protobuf:"bytes,2,opt,name=regKey,oneof"`
}
type Request_CredIssue struct {
	CredIssue *CredIssueRequest `protobuf:"bytes,3,opt,name=credIssue,oneof"`
}
type Request_CredProve struct {
	CredProve *CredProof `protobuf:"bytes,4,opt,name=credProve,oneof"`
}

func (*Request_Empty) isRequest_Type()     {}
func (*Request_RegKey) isRequest_Type()    {}
func (*Request_CredIssue) isRequest_Type() {}
func (*Request_CredProve) isRequest_Type() {}

func (m *Request) GetType() isRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Request) GetEmpty() *Empty {
	if x, ok := m.GetType().(*Request_Empty); ok {
		return x.Empty
	}
	return nil
}

func (m *Request) GetRegKey() string {
	if x, ok := m.GetType().(*Request_RegKey); ok {
		return x.RegKey
	}
	return ""
}

func (m *Request) GetCredIssue() *CredIssueRequest {
	if x, ok := m.GetType().(*Request_CredIssue); ok {
		return x.CredIssue
	}
	return nil
}

func (m *Request) GetCredProve() *CredProof {
	if x, ok := m.GetType().(*Request_CredProve); ok {
		return x.CredProve
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_Empty)(nil),
		(*Request_RegKey)(nil),
		(*Request_CredIssue)(nil),
		(*Request_CredProve)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// type
	switch x := m.Type.(type) {
	case *Request_Empty:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Empty); err != nil {
			return err
		}
	case *Request_RegKey:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.RegKey)
	case *Request_CredIssue:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CredIssue); err != nil {
			return err
		}
	case *Request_CredProve:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CredProve); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.Type has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 1: // type.empty
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Empty)
		err := b.DecodeMessage(msg)
		m.Type = &Request_Empty{msg}
		return true, err
	case 2: // type.regKey
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Type = &Request_RegKey{x}
		return true, err
	case 3: // type.credIssue
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CredIssueRequest)
		err := b.DecodeMessage(msg)
		m.Type = &Request_CredIssue{msg}
		return true, err
	case 4: // type.credProve
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CredProof)
		err := b.DecodeMessage(msg)
		m.Type = &Request_CredProve{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// type
	switch x := m.Type.(type) {
	case *Request_Empty:
		s := proto.Size(x.Empty)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_RegKey:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.RegKey)))
		n += len(x.RegKey)
	case *Request_CredIssue:
		s := proto.Size(x.CredIssue)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_CredProve:
		s := proto.Size(x.CredProve)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Response struct {
	// Types that are valid to be assigned to Type:
	//	*Response_Nonce
	//	*Response_IssuedCred
	//	*Response_SessionKey
	Type isResponse_Type `protobuf_oneof:"type"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isResponse_Type interface {
	isResponse_Type()
}

type Response_Nonce struct {
	Nonce []byte `protobuf:"bytes,1,opt,name=nonce,proto3,oneof"`
}
type Response_IssuedCred struct {
	IssuedCred *IssuedCred `protobuf:"bytes,2,opt,name=issuedCred,oneof"`
}
type Response_SessionKey struct {
	SessionKey string `protobuf:"bytes,3,opt,name=sessionKey,oneof"`
}

func (*Response_Nonce) isResponse_Type()      {}
func (*Response_IssuedCred) isResponse_Type() {}
func (*Response_SessionKey) isResponse_Type() {}

func (m *Response) GetType() isResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Response) GetNonce() []byte {
	if x, ok := m.GetType().(*Response_Nonce); ok {
		return x.Nonce
	}
	return nil
}

func (m *Response) GetIssuedCred() *IssuedCred {
	if x, ok := m.GetType().(*Response_IssuedCred); ok {
		return x.IssuedCred
	}
	return nil
}

func (m *Response) GetSessionKey() string {
	if x, ok := m.GetType().(*Response_SessionKey); ok {
		return x.SessionKey
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_Nonce)(nil),
		(*Response_IssuedCred)(nil),
		(*Response_SessionKey)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// type
	switch x := m.Type.(type) {
	case *Response_Nonce:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Nonce)
	case *Response_IssuedCred:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IssuedCred); err != nil {
			return err
		}
	case *Response_SessionKey:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.SessionKey)
	case nil:
	default:
		return fmt.Errorf("Response.Type has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 1: // type.nonce
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Type = &Response_Nonce{x}
		return true, err
	case 2: // type.issuedCred
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IssuedCred)
		err := b.DecodeMessage(msg)
		m.Type = &Response_IssuedCred{msg}
		return true, err
	case 3: // type.sessionKey
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Type = &Response_SessionKey{x}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// type
	switch x := m.Type.(type) {
	case *Response_Nonce:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Nonce)))
		n += len(x.Nonce)
	case *Response_IssuedCred:
		s := proto.Size(x.IssuedCred)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_SessionKey:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.SessionKey)))
		n += len(x.SessionKey)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SchnorrGroup struct {
	P []byte `protobuf:"bytes,2,opt,name=p,proto3" json:"p,omitempty"`
	G []byte `protobuf:"bytes,3,opt,name=g,proto3" json:"g,omitempty"`
	Q []byte `protobuf:"bytes,4,opt,name=q,proto3" json:"q,omitempty"`
}

func (m *SchnorrGroup) Reset()                    { *m = SchnorrGroup{} }
func (m *SchnorrGroup) String() string            { return proto.CompactTextString(m) }
func (*SchnorrGroup) ProtoMessage()               {}
func (*SchnorrGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SchnorrGroup) GetP() []byte {
	if m != nil {
		return m.P
	}
	return nil
}

func (m *SchnorrGroup) GetG() []byte {
	if m != nil {
		return m.G
	}
	return nil
}

func (m *SchnorrGroup) GetQ() []byte {
	if m != nil {
		return m.Q
	}
	return nil
}

type PedersenParams struct {
	SchnorrGroup *SchnorrGroup `protobuf:"bytes,1,opt,name=schnorrGroup" json:"schnorrGroup,omitempty"`
	H            []byte        `protobuf:"bytes,2,opt,name=h,proto3" json:"h,omitempty"`
}

func (m *PedersenParams) Reset()                    { *m = PedersenParams{} }
func (m *PedersenParams) String() string            { return proto.CompactTextString(m) }
func (*PedersenParams) ProtoMessage()               {}
func (*PedersenParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PedersenParams) GetSchnorrGroup() *SchnorrGroup {
	if m != nil {
		return m.SchnorrGroup
	}
	return nil
}

func (m *PedersenParams) GetH() []byte {
	if m != nil {
		return m.H
	}
	return nil
}

type PubKey struct {
	N              []byte          `protobuf:"bytes,1,opt,name=n,proto3" json:"n,omitempty"`
	S              []byte          `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	Z              []byte          `protobuf:"bytes,3,opt,name=z,proto3" json:"z,omitempty"`
	RsKnown        [][]byte        `protobuf:"bytes,4,rep,name=rsKnown,proto3" json:"rsKnown,omitempty"`
	RsCommitted    [][]byte        `protobuf:"bytes,5,rep,name=rsCommitted,proto3" json:"rsCommitted,omitempty"`
	RsHidden       [][]byte        `protobuf:"bytes,6,rep,name=rsHidden,proto3" json:"rsHidden,omitempty"`
	PedersenParams *PedersenParams `protobuf:"bytes,7,opt,name=pedersenParams" json:"pedersenParams,omitempty"`
	N1             []byte          `protobuf:"bytes,8,opt,name=n1,proto3" json:"n1,omitempty"`
	G              []byte          `protobuf:"bytes,9,opt,name=g,proto3" json:"g,omitempty"`
	H              []byte          `protobuf:"bytes,10,opt,name=h,proto3" json:"h,omitempty"`
}

func (m *PubKey) Reset()                    { *m = PubKey{} }
func (m *PubKey) String() string            { return proto.CompactTextString(m) }
func (*PubKey) ProtoMessage()               {}
func (*PubKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PubKey) GetN() []byte {
	if m != nil {
		return m.N
	}
	return nil
}

func (m *PubKey) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *PubKey) GetZ() []byte {
	if m != nil {
		return m.Z
	}
	return nil
}

func (m *PubKey) GetRsKnown() [][]byte {
	if m != nil {
		return m.RsKnown
	}
	return nil
}

func (m *PubKey) GetRsCommitted() [][]byte {
	if m != nil {
		return m.RsCommitted
	}
	return nil
}

func (m *PubKey) GetRsHidden() [][]byte {
	if m != nil {
		return m.RsHidden
	}
	return nil
}

func (m *PubKey) GetPedersenParams() *PedersenParams {
	if m != nil {
		return m.PedersenParams
	}
	return nil
}

func (m *PubKey) GetN1() []byte {
	if m != nil {
		return m.N1
	}
	return nil
}

func (m *PubKey) GetG() []byte {
	if m != nil {
		return m.G
	}
	return nil
}

func (m *PubKey) GetH() []byte {
	if m != nil {
		return m.H
	}
	return nil
}

type Params struct {
	// There are only a few possibilities for RhoBitLen. 256 implies that the modulus
	// bit length is 2048
	RhoBitLen         int32 `protobuf:"varint,1,opt,name=RhoBitLen" json:"RhoBitLen,omitempty"`
	NLength           int32 `protobuf:"varint,2,opt,name=NLength" json:"NLength,omitempty"`
	KnownAttrsNum     int32 `protobuf:"varint,3,opt,name=KnownAttrsNum" json:"KnownAttrsNum,omitempty"`
	CommittedAttrsNum int32 `protobuf:"varint,4,opt,name=CommittedAttrsNum" json:"CommittedAttrsNum,omitempty"`
	// knows only commitments
	HiddenAttrsNum int32 `protobuf:"varint,5,opt,name=HiddenAttrsNum" json:"HiddenAttrsNum,omitempty"`
	// receiver
	AttrBitLen int32 `protobuf:"varint,6,opt,name=AttrBitLen" json:"AttrBitLen,omitempty"`
	HashBitLen int32 `protobuf:"varint,7,opt,name=HashBitLen" json:"HashBitLen,omitempty"`
	// Fiat-Shamir
	SecParam int32 `protobuf:"varint,8,opt,name=SecParam" json:"SecParam,omitempty"`
	EBitLen  int32 `protobuf:"varint,9,opt,name=EBitLen" json:"EBitLen,omitempty"`
	E1BitLen int32 `protobuf:"varint,10,opt,name=E1BitLen" json:"E1BitLen,omitempty"`
	// from
	VBitLen        int32 `protobuf:"varint,11,opt,name=VBitLen" json:"VBitLen,omitempty"`
	ChallengeSpace int32 `protobuf:"varint,12,opt,name=ChallengeSpace" json:"ChallengeSpace,omitempty"`
}

func (m *Params) Reset()                    { *m = Params{} }
func (m *Params) String() string            { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()               {}
func (*Params) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Params) GetRhoBitLen() int32 {
	if m != nil {
		return m.RhoBitLen
	}
	return 0
}

func (m *Params) GetNLength() int32 {
	if m != nil {
		return m.NLength
	}
	return 0
}

func (m *Params) GetKnownAttrsNum() int32 {
	if m != nil {
		return m.KnownAttrsNum
	}
	return 0
}

func (m *Params) GetCommittedAttrsNum() int32 {
	if m != nil {
		return m.CommittedAttrsNum
	}
	return 0
}

func (m *Params) GetHiddenAttrsNum() int32 {
	if m != nil {
		return m.HiddenAttrsNum
	}
	return 0
}

func (m *Params) GetAttrBitLen() int32 {
	if m != nil {
		return m.AttrBitLen
	}
	return 0
}

func (m *Params) GetHashBitLen() int32 {
	if m != nil {
		return m.HashBitLen
	}
	return 0
}

func (m *Params) GetSecParam() int32 {
	if m != nil {
		return m.SecParam
	}
	return 0
}

func (m *Params) GetEBitLen() int32 {
	if m != nil {
		return m.EBitLen
	}
	return 0
}

func (m *Params) GetE1BitLen() int32 {
	if m != nil {
		return m.E1BitLen
	}
	return 0
}

func (m *Params) GetVBitLen() int32 {
	if m != nil {
		return m.VBitLen
	}
	return 0
}

func (m *Params) GetChallengeSpace() int32 {
	if m != nil {
		return m.ChallengeSpace
	}
	return 0
}

type PublicParams struct {
	PubKey *PubKey `protobuf:"bytes,1,opt,name=pubKey" json:"pubKey,omitempty"`
	Params *Params `protobuf:"bytes,2,opt,name=params" json:"params,omitempty"`
}

func (m *PublicParams) Reset()                    { *m = PublicParams{} }
func (m *PublicParams) String() string            { return proto.CompactTextString(m) }
func (*PublicParams) ProtoMessage()               {}
func (*PublicParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PublicParams) GetPubKey() *PubKey {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *PublicParams) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type CredIssueRequest struct {
	Nym                      []byte             `protobuf:"bytes,1,opt,name=Nym,proto3" json:"Nym,omitempty"`
	KnownAttrs               [][]byte           `protobuf:"bytes,2,rep,name=KnownAttrs,proto3" json:"KnownAttrs,omitempty"`
	CommitmentsOfAttrs       [][]byte           `protobuf:"bytes,3,rep,name=CommitmentsOfAttrs,proto3" json:"CommitmentsOfAttrs,omitempty"`
	NymProof                 *FiatShamir        `protobuf:"bytes,4,opt,name=NymProof" json:"NymProof,omitempty"`
	U                        []byte             `protobuf:"bytes,5,opt,name=U,proto3" json:"U,omitempty"`
	UProof                   *FiatShamirAlsoNeg `protobuf:"bytes,6,opt,name=UProof" json:"UProof,omitempty"`
	CommitmentsOfAttrsProofs []*FiatShamir      `protobuf:"bytes,7,rep,name=CommitmentsOfAttrsProofs" json:"CommitmentsOfAttrsProofs,omitempty"`
	Nonce                    []byte             `protobuf:"bytes,8,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	RegKey                   string             `protobuf:"bytes,9,opt,name=RegKey" json:"RegKey,omitempty"`
}

func (m *CredIssueRequest) Reset()                    { *m = CredIssueRequest{} }
func (m *CredIssueRequest) String() string            { return proto.CompactTextString(m) }
func (*CredIssueRequest) ProtoMessage()               {}
func (*CredIssueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CredIssueRequest) GetNym() []byte {
	if m != nil {
		return m.Nym
	}
	return nil
}

func (m *CredIssueRequest) GetKnownAttrs() [][]byte {
	if m != nil {
		return m.KnownAttrs
	}
	return nil
}

func (m *CredIssueRequest) GetCommitmentsOfAttrs() [][]byte {
	if m != nil {
		return m.CommitmentsOfAttrs
	}
	return nil
}

func (m *CredIssueRequest) GetNymProof() *FiatShamir {
	if m != nil {
		return m.NymProof
	}
	return nil
}

func (m *CredIssueRequest) GetU() []byte {
	if m != nil {
		return m.U
	}
	return nil
}

func (m *CredIssueRequest) GetUProof() *FiatShamirAlsoNeg {
	if m != nil {
		return m.UProof
	}
	return nil
}

func (m *CredIssueRequest) GetCommitmentsOfAttrsProofs() []*FiatShamir {
	if m != nil {
		return m.CommitmentsOfAttrsProofs
	}
	return nil
}

func (m *CredIssueRequest) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *CredIssueRequest) GetRegKey() string {
	if m != nil {
		return m.RegKey
	}
	return ""
}

type Cred struct {
	A   []byte `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	E   []byte `protobuf:"bytes,2,opt,name=E,proto3" json:"E,omitempty"`
	V11 []byte `protobuf:"bytes,3,opt,name=V11,proto3" json:"V11,omitempty"`
}

func (m *Cred) Reset()                    { *m = Cred{} }
func (m *Cred) String() string            { return proto.CompactTextString(m) }
func (*Cred) ProtoMessage()               {}
func (*Cred) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Cred) GetA() []byte {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *Cred) GetE() []byte {
	if m != nil {
		return m.E
	}
	return nil
}

func (m *Cred) GetV11() []byte {
	if m != nil {
		return m.V11
	}
	return nil
}

type IssuedCred struct {
	Cred   *Cred              `protobuf:"bytes,1,opt,name=cred" json:"cred,omitempty"`
	AProof *FiatShamirAlsoNeg `protobuf:"bytes,2,opt,name=AProof" json:"AProof,omitempty"`
}

func (m *IssuedCred) Reset()                    { *m = IssuedCred{} }
func (m *IssuedCred) String() string            { return proto.CompactTextString(m) }
func (*IssuedCred) ProtoMessage()               {}
func (*IssuedCred) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IssuedCred) GetCred() *Cred {
	if m != nil {
		return m.Cred
	}
	return nil
}

func (m *IssuedCred) GetAProof() *FiatShamirAlsoNeg {
	if m != nil {
		return m.AProof
	}
	return nil
}

type CredUpdateRequest struct {
	Nym           []byte   `protobuf:"bytes,1,opt,name=Nym,proto3" json:"Nym,omitempty"`
	Nonce         []byte   `protobuf:"bytes,2,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	NewKnownAttrs [][]byte `protobuf:"bytes,3,rep,name=NewKnownAttrs,proto3" json:"NewKnownAttrs,omitempty"`
}

func (m *CredUpdateRequest) Reset()                    { *m = CredUpdateRequest{} }
func (m *CredUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*CredUpdateRequest) ProtoMessage()               {}
func (*CredUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CredUpdateRequest) GetNym() []byte {
	if m != nil {
		return m.Nym
	}
	return nil
}

func (m *CredUpdateRequest) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *CredUpdateRequest) GetNewKnownAttrs() [][]byte {
	if m != nil {
		return m.NewKnownAttrs
	}
	return nil
}

type CredProof struct {
	A                          []byte             `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	Proof                      *FiatShamirAlsoNeg `protobuf:"bytes,2,opt,name=Proof" json:"Proof,omitempty"`
	KnownAttrs                 [][]byte           `protobuf:"bytes,3,rep,name=KnownAttrs,proto3" json:"KnownAttrs,omitempty"`
	CommitmentsOfAttrs         [][]byte           `protobuf:"bytes,4,rep,name=CommitmentsOfAttrs,proto3" json:"CommitmentsOfAttrs,omitempty"`
	RevealedKnownAttrs         []int32            `protobuf:"varint,5,rep,packed,name=RevealedKnownAttrs" json:"RevealedKnownAttrs,omitempty"`
	RevealedCommitmentsOfAttrs []int32            `protobuf:"varint,6,rep,packed,name=RevealedCommitmentsOfAttrs" json:"RevealedCommitmentsOfAttrs,omitempty"`
}

func (m *CredProof) Reset()                    { *m = CredProof{} }
func (m *CredProof) String() string            { return proto.CompactTextString(m) }
func (*CredProof) ProtoMessage()               {}
func (*CredProof) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CredProof) GetA() []byte {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *CredProof) GetProof() *FiatShamirAlsoNeg {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *CredProof) GetKnownAttrs() [][]byte {
	if m != nil {
		return m.KnownAttrs
	}
	return nil
}

func (m *CredProof) GetCommitmentsOfAttrs() [][]byte {
	if m != nil {
		return m.CommitmentsOfAttrs
	}
	return nil
}

func (m *CredProof) GetRevealedKnownAttrs() []int32 {
	if m != nil {
		return m.RevealedKnownAttrs
	}
	return nil
}

func (m *CredProof) GetRevealedCommitmentsOfAttrs() []int32 {
	if m != nil {
		return m.RevealedCommitmentsOfAttrs
	}
	return nil
}

type FiatShamir struct {
	// Used for example for SchnorrProof and RepresentationProof where challenge is constructed by prover
	// using hash function.
	// Note that here we don't have A and B as in SchnorrProofRandomData because usually when proving
	// the knowledge of X such that A^X = B, A is known beforehand (as part of public key).
	// So here ProofRandomData is actually only X.
	ProofRandomData []byte   `protobuf:"bytes,1,opt,name=ProofRandomData,proto3" json:"ProofRandomData,omitempty"`
	Challenge       []byte   `protobuf:"bytes,2,opt,name=Challenge,proto3" json:"Challenge,omitempty"`
	ProofData       [][]byte `protobuf:"bytes,3,rep,name=ProofData,proto3" json:"ProofData,omitempty"`
}

func (m *FiatShamir) Reset()                    { *m = FiatShamir{} }
func (m *FiatShamir) String() string            { return proto.CompactTextString(m) }
func (*FiatShamir) ProtoMessage()               {}
func (*FiatShamir) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *FiatShamir) GetProofRandomData() []byte {
	if m != nil {
		return m.ProofRandomData
	}
	return nil
}

func (m *FiatShamir) GetChallenge() []byte {
	if m != nil {
		return m.Challenge
	}
	return nil
}

func (m *FiatShamir) GetProofData() [][]byte {
	if m != nil {
		return m.ProofData
	}
	return nil
}

type FiatShamirAlsoNeg struct {
	// For proofs where proof data can be negative (see RepresentationProof).
	ProofRandomData []byte   `protobuf:"bytes,1,opt,name=ProofRandomData,proto3" json:"ProofRandomData,omitempty"`
	Challenge       []byte   `protobuf:"bytes,2,opt,name=Challenge,proto3" json:"Challenge,omitempty"`
	ProofData       []string `protobuf:"bytes,3,rep,name=ProofData" json:"ProofData,omitempty"`
}

func (m *FiatShamirAlsoNeg) Reset()                    { *m = FiatShamirAlsoNeg{} }
func (m *FiatShamirAlsoNeg) String() string            { return proto.CompactTextString(m) }
func (*FiatShamirAlsoNeg) ProtoMessage()               {}
func (*FiatShamirAlsoNeg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *FiatShamirAlsoNeg) GetProofRandomData() []byte {
	if m != nil {
		return m.ProofRandomData
	}
	return nil
}

func (m *FiatShamirAlsoNeg) GetChallenge() []byte {
	if m != nil {
		return m.Challenge
	}
	return nil
}

func (m *FiatShamirAlsoNeg) GetProofData() []string {
	if m != nil {
		return m.ProofData
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "clpb.Request")
	proto.RegisterType((*Response)(nil), "clpb.Response")
	proto.RegisterType((*Empty)(nil), "clpb.Empty")
	proto.RegisterType((*SchnorrGroup)(nil), "clpb.SchnorrGroup")
	proto.RegisterType((*PedersenParams)(nil), "clpb.PedersenParams")
	proto.RegisterType((*PubKey)(nil), "clpb.PubKey")
	proto.RegisterType((*Params)(nil), "clpb.Params")
	proto.RegisterType((*PublicParams)(nil), "clpb.PublicParams")
	proto.RegisterType((*CredIssueRequest)(nil), "clpb.CredIssueRequest")
	proto.RegisterType((*Cred)(nil), "clpb.Cred")
	proto.RegisterType((*IssuedCred)(nil), "clpb.IssuedCred")
	proto.RegisterType((*CredUpdateRequest)(nil), "clpb.CredUpdateRequest")
	proto.RegisterType((*CredProof)(nil), "clpb.CredProof")
	proto.RegisterType((*FiatShamir)(nil), "clpb.FiatShamir")
	proto.RegisterType((*FiatShamirAlsoNeg)(nil), "clpb.FiatShamirAlsoNeg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AnonCreds service

type AnonCredsClient interface {
	GetPublicParams(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PublicParams, error)
	Issue(ctx context.Context, opts ...grpc.CallOption) (AnonCreds_IssueClient, error)
	Update(ctx context.Context, in *CredUpdateRequest, opts ...grpc.CallOption) (*IssuedCred, error)
	Prove(ctx context.Context, opts ...grpc.CallOption) (AnonCreds_ProveClient, error)
}

type anonCredsClient struct {
	cc *grpc.ClientConn
}

func NewAnonCredsClient(cc *grpc.ClientConn) AnonCredsClient {
	return &anonCredsClient{cc}
}

func (c *anonCredsClient) GetPublicParams(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PublicParams, error) {
	out := new(PublicParams)
	err := grpc.Invoke(ctx, "/clpb.AnonCreds/GetPublicParams", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anonCredsClient) Issue(ctx context.Context, opts ...grpc.CallOption) (AnonCreds_IssueClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_AnonCreds_serviceDesc.Streams[0], c.cc, "/clpb.AnonCreds/Issue", opts...)
	if err != nil {
		return nil, err
	}
	x := &anonCredsIssueClient{stream}
	return x, nil
}

type AnonCreds_IssueClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type anonCredsIssueClient struct {
	grpc.ClientStream
}

func (x *anonCredsIssueClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *anonCredsIssueClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *anonCredsClient) Update(ctx context.Context, in *CredUpdateRequest, opts ...grpc.CallOption) (*IssuedCred, error) {
	out := new(IssuedCred)
	err := grpc.Invoke(ctx, "/clpb.AnonCreds/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anonCredsClient) Prove(ctx context.Context, opts ...grpc.CallOption) (AnonCreds_ProveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_AnonCreds_serviceDesc.Streams[1], c.cc, "/clpb.AnonCreds/Prove", opts...)
	if err != nil {
		return nil, err
	}
	x := &anonCredsProveClient{stream}
	return x, nil
}

type AnonCreds_ProveClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type anonCredsProveClient struct {
	grpc.ClientStream
}

func (x *anonCredsProveClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *anonCredsProveClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for AnonCreds service

type AnonCredsServer interface {
	GetPublicParams(context.Context, *Empty) (*PublicParams, error)
	Issue(AnonCreds_IssueServer) error
	Update(context.Context, *CredUpdateRequest) (*IssuedCred, error)
	Prove(AnonCreds_ProveServer) error
}

func RegisterAnonCredsServer(s *grpc.Server, srv AnonCredsServer) {
	s.RegisterService(&_AnonCreds_serviceDesc, srv)
}

func _AnonCreds_GetPublicParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnonCredsServer).GetPublicParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clpb.AnonCreds/GetPublicParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnonCredsServer).GetPublicParams(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnonCreds_Issue_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnonCredsServer).Issue(&anonCredsIssueServer{stream})
}

type AnonCreds_IssueServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type anonCredsIssueServer struct {
	grpc.ServerStream
}

func (x *anonCredsIssueServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *anonCredsIssueServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AnonCreds_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnonCredsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clpb.AnonCreds/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnonCredsServer).Update(ctx, req.(*CredUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnonCreds_Prove_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnonCredsServer).Prove(&anonCredsProveServer{stream})
}

type AnonCreds_ProveServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type anonCredsProveServer struct {
	grpc.ServerStream
}

func (x *anonCredsProveServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *anonCredsProveServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AnonCreds_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clpb.AnonCreds",
	HandlerType: (*AnonCredsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicParams",
			Handler:    _AnonCreds_GetPublicParams_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AnonCreds_Update_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Issue",
			Handler:       _AnonCreds_Issue_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Prove",
			Handler:       _AnonCreds_Prove_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "anauth/cl/clpb/cl.proto",
}

func init() { proto.RegisterFile("anauth/cl/clpb/cl.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1045 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0x25, 0x91, 0xb2, 0x46, 0x8a, 0xec, 0x2c, 0x82, 0x98, 0x10, 0x8a, 0x22, 0x60, 0x83,
	0xc0, 0x87, 0x56, 0xae, 0xdd, 0xb4, 0xe8, 0xa1, 0x28, 0x20, 0xbb, 0x6a, 0x1c, 0x24, 0x50, 0x8d,
	0x35, 0xec, 0x43, 0x80, 0x1e, 0x68, 0x69, 0x23, 0x0a, 0x15, 0x7f, 0xcc, 0xa5, 0x12, 0xc8, 0xa7,
	0x1e, 0x7b, 0xec, 0xeb, 0xf4, 0x3d, 0x7a, 0xed, 0x5b, 0xf4, 0x01, 0x3a, 0x3b, 0xbb, 0xfc, 0x93,
	0x9d, 0xd4, 0x97, 0x00, 0x41, 0xc4, 0x99, 0xf9, 0x66, 0x77, 0xe7, 0x9b, 0xd9, 0xcf, 0x0b, 0x7b,
	0x7e, 0xe4, 0xaf, 0xb2, 0xe0, 0x60, 0xba, 0xc4, 0x7f, 0xc9, 0x15, 0xfe, 0x37, 0x4c, 0xd2, 0x38,
	0x8b, 0x59, 0x4b, 0x99, 0xde, 0x5f, 0x16, 0xb4, 0xb9, 0xb8, 0x5e, 0x09, 0x99, 0xb1, 0x2f, 0xc0,
	0x16, 0x61, 0x92, 0xad, 0x5d, 0xeb, 0x89, 0xb5, 0xdf, 0x3d, 0xea, 0x0e, 0x15, 0x62, 0x38, 0x56,
	0xae, 0xd3, 0x2d, 0xae, 0x63, 0xcc, 0x05, 0x27, 0x15, 0xf3, 0x57, 0x62, 0xed, 0x36, 0x10, 0xd5,
	0xc1, 0x80, 0xb1, 0xd9, 0x77, 0xd0, 0x99, 0xa6, 0x62, 0xf6, 0x52, 0xca, 0x95, 0x70, 0x9b, 0xb4,
	0xc4, 0x63, 0xbd, 0xc4, 0x49, 0xee, 0x36, 0x3b, 0x61, 0x52, 0x09, 0x65, 0x07, 0x3a, 0xef, 0x2c,
	0x8d, 0xdf, 0x09, 0xb7, 0x45, 0x79, 0x3b, 0x65, 0x1e, 0xba, 0xe3, 0xb7, 0x79, 0x02, 0x61, 0x8e,
	0x1d, 0x68, 0x65, 0xeb, 0x44, 0x78, 0xbf, 0x5b, 0xb0, 0xcd, 0x85, 0x4c, 0xe2, 0x48, 0x0a, 0xf6,
	0x18, 0xec, 0x28, 0x8e, 0xa6, 0x82, 0x0e, 0xdf, 0x53, 0xe7, 0x25, 0x93, 0x1d, 0x01, 0x2c, 0xd4,
	0x36, 0x33, 0xb5, 0x18, 0x9d, 0xb9, 0x7b, 0xb4, 0xab, 0x97, 0x7f, 0x59, 0xf8, 0x11, 0x5e, 0x41,
	0xb1, 0x27, 0x00, 0x52, 0x48, 0xb9, 0x88, 0x23, 0x55, 0x67, 0xd3, 0xd4, 0x59, 0xf1, 0x15, 0x47,
	0x68, 0x83, 0x4d, 0xfc, 0x78, 0xdf, 0x43, 0xef, 0x7c, 0x1a, 0x44, 0x71, 0x9a, 0xbe, 0x48, 0xe3,
	0x55, 0xc2, 0x7a, 0x60, 0x25, 0xb4, 0x5b, 0x8f, 0x5b, 0x64, 0xcd, 0x69, 0x1d, 0xb4, 0xe6, 0xca,
	0xba, 0xa6, 0x42, 0xd1, 0xba, 0xf6, 0x2e, 0xa1, 0x7f, 0x26, 0x66, 0x22, 0x95, 0x22, 0x3a, 0xf3,
	0x53, 0x3f, 0x94, 0x48, 0x64, 0x4f, 0x56, 0xd6, 0x32, 0xed, 0x60, 0xfa, 0xd0, 0xd5, 0x5d, 0x78,
	0x0d, 0xa7, 0xd6, 0x0d, 0xf2, 0x3d, 0x03, 0xef, 0x5f, 0x0b, 0x9c, 0xb3, 0xd5, 0x95, 0xea, 0x0c,
	0x06, 0x22, 0xcd, 0x0b, 0xb7, 0x22, 0x65, 0xc9, 0x1c, 0x26, 0x95, 0x75, 0x93, 0x1f, 0xed, 0x06,
	0xbb, 0xdb, 0x4e, 0xe5, 0xab, 0x28, 0x7e, 0x1f, 0xe1, 0x01, 0x9b, 0xe8, 0xcb, 0x4d, 0xe4, 0xa4,
	0x9b, 0xca, 0x93, 0x38, 0x0c, 0x17, 0x59, 0x86, 0x44, 0xda, 0x14, 0xad, 0xba, 0xd8, 0x00, 0xb6,
	0x53, 0x79, 0xba, 0x98, 0xcd, 0x44, 0xe4, 0x3a, 0x14, 0x2e, 0x6c, 0xf6, 0x03, 0xf4, 0x93, 0x5a,
	0x91, 0x6e, 0x9b, 0x8a, 0x7a, 0xa4, 0x8b, 0xaa, 0x13, 0xc0, 0x37, 0xb0, 0xac, 0x0f, 0x8d, 0xe8,
	0xd0, 0xdd, 0xa6, 0x43, 0xe2, 0x97, 0xa6, 0xb3, 0x53, 0xa1, 0x33, 0x70, 0x21, 0x2f, 0xfb, 0xcf,
	0x26, 0x96, 0xad, 0xd3, 0x3e, 0x83, 0x0e, 0x0f, 0xe2, 0xe3, 0x45, 0xf6, 0x5a, 0xe8, 0xf2, 0x6d,
	0x5e, 0x3a, 0x54, 0xa9, 0x13, 0xfc, 0x9d, 0x67, 0x9a, 0x33, 0x9b, 0xe7, 0x26, 0x7b, 0x0a, 0x0f,
	0xa8, 0xe6, 0x51, 0x96, 0xa5, 0x72, 0xb2, 0x0a, 0x89, 0x1e, 0x9b, 0xd7, 0x9d, 0xec, 0x4b, 0x78,
	0x58, 0xd4, 0x5e, 0x20, 0x5b, 0x84, 0xbc, 0x1d, 0x60, 0xcf, 0xa0, 0xaf, 0xa9, 0x28, 0xa0, 0x36,
	0x41, 0x37, 0xbc, 0xec, 0x73, 0x00, 0xf5, 0x6d, 0x0e, 0xed, 0x10, 0xa6, 0xe2, 0x51, 0xf1, 0x53,
	0x5f, 0x06, 0x26, 0xde, 0xd6, 0xf1, 0xd2, 0xa3, 0x9a, 0x70, 0x2e, 0xa6, 0x44, 0x00, 0x11, 0x66,
	0xf3, 0xc2, 0x56, 0x15, 0x8f, 0x4d, 0x62, 0x47, 0x57, 0x3c, 0x2e, 0xb3, 0xc6, 0x87, 0x26, 0x04,
	0x3a, 0x2b, 0xb7, 0x55, 0xd6, 0xa5, 0x09, 0x75, 0x75, 0x96, 0x31, 0x55, 0x4d, 0x27, 0x81, 0xbf,
	0x5c, 0x22, 0x6b, 0xe2, 0x3c, 0xf1, 0xf1, 0xee, 0xf5, 0x74, 0x4d, 0x75, 0xaf, 0xf7, 0x06, 0x7a,
	0x38, 0x88, 0xcb, 0xc5, 0xd4, 0xf4, 0xe5, 0x29, 0x38, 0x09, 0x0d, 0xa6, 0x99, 0xec, 0x9e, 0x19,
	0x02, 0xf2, 0x71, 0x13, 0x23, 0x94, 0x1e, 0x95, 0x46, 0x0d, 0xa5, 0x47, 0xc4, 0xc4, 0xbc, 0x7f,
	0x1a, 0xb0, 0xbb, 0x29, 0x2f, 0x6c, 0x17, 0x9a, 0x93, 0x75, 0x68, 0x26, 0x5e, 0x7d, 0x2a, 0xda,
	0xca, 0xee, 0xe1, 0x82, 0x6a, 0x3a, 0x2b, 0x1e, 0x36, 0x04, 0xa6, 0x7b, 0x16, 0x8a, 0x28, 0x93,
	0xbf, 0xbc, 0xd5, 0xb8, 0x26, 0xe1, 0xee, 0x88, 0x60, 0xf3, 0xb7, 0x71, 0x59, 0xd2, 0x26, 0x23,
	0x59, 0x46, 0x53, 0x7e, 0x5e, 0xf8, 0xd9, 0x79, 0xe0, 0x87, 0x8b, 0x94, 0x17, 0x08, 0x35, 0xa1,
	0x17, 0xd4, 0x6f, 0x9c, 0xd0, 0x0b, 0xd4, 0x3b, 0xe7, 0x42, 0x67, 0x3a, 0x94, 0xb9, 0xb7, 0x99,
	0x39, 0x5a, 0xca, 0x78, 0x22, 0xe6, 0xdc, 0xc0, 0xd8, 0x6b, 0x70, 0x6f, 0x1f, 0x81, 0x42, 0xea,
	0x1a, 0x35, 0xef, 0xdc, 0xfc, 0x83, 0x19, 0xec, 0x11, 0xd8, 0x13, 0x12, 0x4a, 0x7d, 0x9f, 0xb4,
	0x81, 0xf2, 0xe9, 0x70, 0x2d, 0xeb, 0x6a, 0x34, 0x3a, 0xdc, 0x58, 0xde, 0x73, 0x68, 0x91, 0x24,
	0x62, 0x09, 0xa3, 0x5c, 0x42, 0x46, 0xca, 0x1a, 0xe7, 0x12, 0x32, 0x56, 0x74, 0x5f, 0x1e, 0x1e,
	0x1a, 0x11, 0x51, 0x9f, 0xde, 0xaf, 0x00, 0xa5, 0xb8, 0x22, 0xf9, 0x2d, 0x25, 0xde, 0xa6, 0xdb,
	0x50, 0x6a, 0x3b, 0x27, 0xbf, 0x22, 0x64, 0xa4, 0x09, 0x69, 0xfc, 0x0f, 0x21, 0x1a, 0xe6, 0xf9,
	0x78, 0xf5, 0x30, 0xf1, 0x22, 0x99, 0xf9, 0xd9, 0x47, 0x9a, 0x5e, 0x54, 0xda, 0xa8, 0x56, 0x8a,
	0xb7, 0x7b, 0x22, 0xde, 0x57, 0xa6, 0x41, 0x77, 0xb9, 0xee, 0xf4, 0xfe, 0x68, 0x40, 0xa7, 0xf8,
	0xf3, 0xb3, 0x51, 0xfd, 0x57, 0x60, 0xdf, 0xeb, 0xb8, 0x1a, 0xb5, 0x31, 0x7b, 0xcd, 0x7b, 0xce,
	0x5e, 0xeb, 0x83, 0xb3, 0x87, 0x78, 0x2e, 0xde, 0x09, 0x7f, 0x29, 0x66, 0x95, 0x75, 0x95, 0x20,
	0xdb, 0xfc, 0x8e, 0x08, 0xfb, 0x11, 0x06, 0xb9, 0xf7, 0x8e, 0x7d, 0x1c, 0xca, 0xfb, 0x08, 0xc2,
	0x4b, 0x01, 0xca, 0xda, 0xd8, 0x3e, 0xec, 0x50, 0x59, 0xdc, 0x8f, 0x66, 0x71, 0xf8, 0x93, 0x9f,
	0xf9, 0x86, 0x98, 0x4d, 0xb7, 0x92, 0xdf, 0x42, 0x08, 0x4c, 0x0b, 0x4a, 0x87, 0x8a, 0x52, 0x02,
	0xad, 0xa0, 0x49, 0x29, 0x1d, 0xde, 0x1a, 0x1e, 0xde, 0xe2, 0xf3, 0xd3, 0x6d, 0xdd, 0xa9, 0x6c,
	0x7d, 0xf4, 0xb7, 0x05, 0x9d, 0x11, 0xbe, 0x1d, 0x54, 0xf7, 0x25, 0x7b, 0x0e, 0x3b, 0x2f, 0x44,
	0x56, 0x93, 0xaf, 0xea, 0xbb, 0x68, 0xc0, 0x0a, 0xed, 0x2a, 0x00, 0xde, 0x16, 0xca, 0x83, 0xad,
	0xdf, 0x36, 0x0f, 0x74, 0xd8, 0xcc, 0xe8, 0xa0, 0x9f, 0x9b, 0xfa, 0xd1, 0xe2, 0x6d, 0xed, 0x5b,
	0x5f, 0x5b, 0xec, 0x5b, 0x14, 0x04, 0x1a, 0x65, 0xb6, 0x57, 0xde, 0x8d, 0xda, 0x70, 0x0f, 0x6e,
	0xbd, 0x58, 0xf4, 0x26, 0xf4, 0x1e, 0xba, 0xd7, 0x26, 0xc7, 0xfb, 0x6f, 0x9e, 0xcd, 0x17, 0x59,
	0xb0, 0xba, 0x1a, 0x4e, 0xe3, 0xf0, 0x40, 0x84, 0xe1, 0xfa, 0xe6, 0xb7, 0x84, 0x7e, 0x0f, 0xea,
	0x2f, 0xc4, 0x2b, 0x87, 0xde, 0x87, 0xdf, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x11, 0xda,
	0xce, 0x3a, 0x0a, 0x00, 0x00,
}
